version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: moviehub-backend:latest
    container_name: moviehub-backend
    environment:
      # Spring Boot Mongo property name
      - SPRING_DATA_MONGODB_URI=mongodb+srv://movieadmin:StarryNight789.@moviehub.luusdud.mongodb.net/moviehub?retryWrites=true&w=majority&appName=Moviehub

      #  JWT secret for JwtUtil.java
      - JWT_SECRET=Super34565656565565Strong454544554545456Secret45453345Key4566666443452189

      # Optional Spring profile
      - SPRING_PROFILES_ACTIVE=prod

      # Optional server configuration
      - SERVER_PORT=8080
      - SERVER_ADDR=0.0.0.0

    ports:
      - "8080:8080"
    networks:
      - moviehub-net
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: moviehub-frontend:latest
    container_name: moviehub-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - moviehub-net
    restart: always

networks:
  moviehub-net:
    driver: bridge
